#pragma once
#include "kernel_config.h"

using Fast128x128Stage4FP32 = cutlass::gemm::device::Gemm<ElementA,
                                                 LayoutA,
                                                 ElementB,
                                                 LayoutB,
                                                 ElementC,
                                                 LayoutC,
                                                 ElementAccumulator,
                                                 OpClass,
                                                 ArchTag,
                                                 LargeThreadBlockShape,
                                                 LargeWarpShape,
                                                 LargeMultiplyAddShape,
                                                 FastFP32EpilogueOp,
                                                 Swizzle,
                                                 kStages,
                                                 kAlignmentA,
                                                 kAlignmentB,
                                                 false,
                                                 OpMMA
                                                 >;

using Fast128x128Stage4FP32MWarp = cutlass::gemm::device::Gemm<ElementA,
                                                 LayoutA,
                                                 ElementB,
                                                 LayoutB,
                                                 ElementC,
                                                 LayoutC,
                                                 ElementAccumulator,
                                                 OpClass,
                                                 ArchTag,
                                                 LargeThreadBlockShape,
                                                 MediumWarpShape,
                                                 LargeMultiplyAddShape,
                                                 FastFP32EpilogueOp,
                                                 Swizzle,
                                                 kStages,
                                                 kAlignmentA,
                                                 kAlignmentB,
                                                 false,
                                                 OpMMA
                                                 >;

using Fallback128x128Stage4FP32 = cutlass::gemm::device::Gemm<ElementA,
                                                 LayoutA,
                                                 ElementB,
                                                 LayoutB,
                                                 ElementC,
                                                 LayoutC,
                                                 ElementAccumulator,
                                                 OpClass,
                                                 ArchTag,
                                                 LargeThreadBlockShape,
                                                 LargeWarpShape,
                                                 LargeMultiplyAddShape,
                                                 FallbackFP32EpilogueOp,
                                                 Swizzle,
                                                 kStages,
                                                 1,
                                                 1,
                                                 false,
                                                 OpMMA
                                                 >;

using Fallback128x128Stage4FP32MWarp = cutlass::gemm::device::Gemm<ElementA,
                                                 LayoutA,
                                                 ElementB,
                                                 LayoutB,
                                                 ElementC,
                                                 LayoutC,
                                                 ElementAccumulator,
                                                 OpClass,
                                                 ArchTag,
                                                 LargeThreadBlockShape,
                                                 MediumWarpShape,
                                                 LargeMultiplyAddShape,
                                                 FallbackFP32EpilogueOp,
                                                 Swizzle,
                                                 kStages,
                                                 kAlignmentA,
                                                 kAlignmentB,
                                                 false,
                                                 OpMMA
                                                 >;
